---
- name: Address Creation
  hosts: cisco_asa
  gather_facts: no
  collections:
    - cisco.asa
  vars:
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_pass: "{{ enable_password }}"  # Use tower credential variable if set

  tasks:
    - name: Address Object creation 
      asa_config:
        lines:
          - network-object host 129.6.15.28
          - network-object host 129.6.15.29
          - network-object host 129.6.15.30
        parents: [object-group network NTP-Servers]
      register: output

    - name: Display version details
      debug:
        var: output