---
- name: Check Cisco ASA version
  hosts: cisco_asa
  gather_facts: no
  collections:
    - cisco.asa
  tasks:
    - name: Get ASA device version info
      asa_command:
        commands:
          - show version
      register: version_output

    - name: Display version details
      debug:
        var: version_output.stdout_lines
