---
- name: Execute Ping Test on Cisco ASA (Chained RAW Command)
  hosts: cisco_asa
  gather_facts: false
  connection: network_cli 

  tasks:
    - name: 1. Execute 'enable' then 'ping 8.8.8.8' via raw
      ansible.builtin.raw:
        # Chain the 'enable' command with the 'ping' command.
        # Ansible will inject the become password automatically after 'enable'
        command: enable ; ping 8.8.8.8
      register: ping_output_raw

    - name: 2. Set Fact for Ping Output
      # Join the list of output lines into a single, clean string
      ansible.builtin.set_fact:
        asa_ping_output: "{{ ping_output_raw.stdout_lines | join('\n') }}"

    - name: 3. Display Ping Results
      ansible.builtin.debug:
        msg: "Ping results from {{ inventory_hostname }}:\n{{ asa_ping_output }}"