---
- name: Get Cisco ASA version without collection modules
  hosts: cisco_asa
  gather_facts: true
  connection: network_cli 

  tasks:
    - name: 1. Execute 'show version' command
      ansible.builtin.cli_command:
        command: show version
      register: version_output

    - name: 2. Extract and Set ASA Version (Simple Slicing Fix)
      ansible.builtin.set_fact:
        asa_version_string: >
          {# Define the exact starting index of the version number: #}
          {# "Cisco Adaptive Security Appliance Software Version " is 57 characters long #}
          {% set raw_version = version_output.stdout[0][57:] %}
          
          {# Grab the first word (the version number) from the sliced string #}
          {{ raw_version.split(' ')[0] | trim }}

    - name: 3. Display the ASA version
      ansible.builtin.debug:
        msg: "ASA Software Version on {{ inventory_hostname }}: {{ asa_version_string }}"