---
- name: Get Cisco ASA version without collection modules
  hosts: cisco_asa
  gather_facts: false
  connection: network_cli 

  tasks:
    - name: 1. Execute 'show version' command
      ansible.builtin.cli_command:
        command: show version
      register: version_output

    - name: 2. Extract and Set ASA Version (Standard Filters Only)
      ansible.builtin.set_fact:
        asa_version_string: >
          {% set start_marker = 'Software Version ' %}
          {% set line = version_output.stdout[0].split('\n') | select('search', start_marker) | first %}
          
          {% if line %}
          {# Find the position after 'Software Version ' #}
          {% set version_start_index = line.find(start_marker) + start_marker | length %}
          {# Slice the string from that index, split by space, and get the first chunk #}
          {{ line[version_start_index:] | split(' ') | select('length') | first | trim }}
          {% else %}
          N/A_FINAL_FAILED
          {% endif %}

    - name: 3. Display the ASA version
      ansible.builtin.debug:
        msg: "ASA Software Version on {{ inventory_hostname }}: {{ asa_version_string }}"