- name: commands runtime on Cisco ASA
  hosts: cisco_asa
  gather_facts: no
  collections:
    - cisco.asa
  vars:
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_pass: "{{ enable_password }}"  # Use tower credential variable if set
    
  tasks:
    - name: Run 'commands runtime'
      asa_command:
        commands: "{{ asa_config_commands }}"
      register: interface_brief_output

    - name: Display commmands runtime output
      debug:
        var: interface_brief_output.stdout_lines
