---
- name: Show connection count on Cisco ASA
  hosts: cisco_asa
  gather_facts: no
  collections:
    - cisco.asa
  vars:
    ansible_network_os: cisco.asa.asa
    ansible_connection: network_cli
    ansible_ssh_transport: paramiko           # Optional if using paramiko transport
    ansible_become: yes
    ansible_become_method: enable
    #ansible_become_pass: "{{ enable_password }}"  # Use tower credential variable if set
  tasks:
    - name: Get connection count
      asa_command:
        commands:
          - show conn count
      register: conn_count_output

    - name: Print connection count output
      debug:
        var: conn_count_output.stdout_lines
