- name: Show IP interface brief on Cisco ASA
  hosts: cisco_asa
  gather_facts: no
  collections:
    - cisco.asa
  tasks:
    - name: Run 'show ip interface brief'
      asa_command:
        commands:
          - show ip interface brief
      register: interface_brief_output

    - name: Display interface brief output
      debug:
        var: interface_brief_output.stdout_lines
