---
- name: Get Cisco ASA Interface Status (Using RAW Module)
  hosts: cisco_asa
  gather_facts: false
  # Note: raw still needs the network_cli connection to work over SSH/Telnet
  connection: network_cli 

  tasks:
    - name: 1. Execute 'show interface ip brief' command via raw
      ansible.builtin.raw:
        # Use the known correct, long-form command
        command: show interface ip brief
      register: int_output_raw

    - name: 2. Set Fact for Interface Output (Cleaned for raw)
      ansible.builtin.set_fact:
        # The output from 'raw' is usually in a list under 'stdout_lines', join them with newlines.
        asa_interfaces: "{{ int_output_raw.stdout_lines | join('\n') }}"

    - name: 3. Display Interface Status Table
      ansible.builtin.debug:
        msg: "Interface IP Brief Status on {{ inventory_hostname }}:\n{{ asa_interfaces }}"