---
- name: Get Cisco ASA Interface Status (Final Working Command)
  hosts: cisco_asa
  gather_facts: false
  connection: network_cli 

  tasks:
    - name: 1. Execute 'show interface ip brief' command
      ansible.builtin.cli_command:
        # Use the confirmed working command
        command: show interface ip brief 
      register: int_output

    - name: 2. Set Fact for Interface Output (Cleaned)
      # Safely set a fact to the raw output, handling potential empty lists
      ansible.builtin.set_fact:
        asa_interfaces: "{{ int_output.stdout[0] | default('Error: No output received') }}"

    - name: 3. Display Interface Status Table
      ansible.builtin.debug:
        msg: "Interface IP Brief Status on {{ inventory_hostname }}:\n{{ asa_interfaces }}"