---
- name: Save running to startup when modified
  hosts: cisco_asa
  gather_facts: no
  collections:
    - cisco.asa
  vars:
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_pass: "{{ enable_password }}"  # Use Tower credential variable if set

  tasks:
    - name: Save running-config to startup-config if modified
      asa_config:
        save_when: modified
      register: output

    - name: Display output
      debug:
        var: output
