- name: Show run ip on Cisco ASA
  hosts: cisco_asa
  gather_facts: no
  collections:
    - cisco.asa
  vars:
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_pass: "{{ enable_password }}"  # Use tower credential variable if set
    
  tasks:
    - name: Run 'show run ip'
      asa_command:
        commands:
          - show run ip
      register: interface_brief_output

    - name: Display interface brief output
      debug:
        var: interface_brief_output.stdout_lines
